$config['protocol'] = 'smtp';
$config['smtp_host'] = 'ssl://smtp.gmail.com'; //change this with your smtp host
$config['smtp_port'] = '465';
$config['smtp_user'] = 'metalcodeifsp@gmail.com';
$config['smtp_pass'] = '#metalcode2017#';
$config['mailtype'] = 'html';
$config['charset']   = 'utf-8';
$config['wordwrap'] = TRUE;
$config['newline'] = "\r\n";
